FIX: Allow use of ArchiveAdmin on unstaged objects.
silverstripe/silverstripe-versioned-admin pull request #167
Opened 2020-08-26 02:34 UTC by sminnee

2020-08-26 05:36 UTC, NightJar approved these changes
Nice work :)

2020-09-04 01:17 UTC, emteknetnz requested changes
Minor recommendation for inline comment

2020-09-04 01:17 UTC, emteknetnz commented on tests/ArchiveAdminTest/SingleStageObject.php
> +    private static $extensions = [
The used of `.versioned` may be a bit confusing for people (myself included) - might we worth putting an inline comment and/or link to https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/02_Developer_Guides/00_Model/10_Versioning.md#applying-the-versioned-extension-to-your-dataobject to say that in enables stageless versioning (_Versions table but not _Live table)

2021-03-30 20:17 UTC, chillu commented
Merging. The inline comment is not a blocker.

2021-03-30 20:17 UTC, merged