API Migrate SilverStripeNagivator
silverstripe/silverstripe-versioned-admin pull request #253
Opened 2022-09-14 02:15 UTC by GuySartorelli

These `SilverStripeNavigatorItem` subclasses are useful for `Versioned` objects without requiring `silverstripe/cms`
I'm not adding them directly to `silverstripe/versioned` because that module has no dependency on `silverstripe/admin` - nor should it.

See also https://github.com/silverstripe/silverstripe-cms/pull/2761

## Parent issue
- https://github.com/silverstripe/silverstripe-admin/issues/1339

2022-09-27 22:07 UTC, GuySartorelli commented
Needs https://github.com/silverstripe/silverstripe-admin/pull/1340 to be merged before it will go green.

2022-10-05 02:58 UTC, sabina-talipova commented
Could you fix lint issues: https://github.com/silverstripe/silverstripe-versioned-admin/actions/runs/3049723059/jobs/5197764881, please.

2022-10-05 03:09 UTC, GuySartorelli commented
Done - I've updated the linting rules to allow the class names, since these are the same class names that were in use in the cms module.
I've also added some items to the `.gitignore` file which shouldn't be committed, but are sometimes present during development.

2022-10-05 19:57 UTC, sabina-talipova requested changes

2022-10-05 19:57 UTC, sabina-talipova commented on tests/Navigator/SilverStripeNavigatorTest.php
> +use SilverStripe\Versioned\Navigator\SilverStripeNavigatorItem_StageLink;
```suggestion
use SilverStripe\VersionedAdmin\Navigator\SilverStripeNavigatorItem_ArchiveLink;
use SilverStripe\VersionedAdmin\Navigator\SilverStripeNavigatorItem_LiveLink;
use SilverStripe\VersionedAdmin\Navigator\SilverStripeNavigatorItem_StageLink;
```

2022-10-05 19:57 UTC, sabina-talipova commented on tests/Navigator/SilverStripeNavigatorTest.php
> +use SilverStripe\Dev\SapphireTest;
```suggestion
use SilverStripe\Dev\SapphireTest;
use SilverStripe\VersionedAdmin\Tests\Navigator\UnstagedRecord;
use SilverStripe\VersionedAdmin\Tests\Navigator\UnversionedRecord;
use SilverStripe\VersionedAdmin\Tests\Navigator\VersionedRecord;
```

2022-10-05 20:55 UTC, GuySartorelli commented on tests/Navigator/SilverStripeNavigatorTest.php
> +use SilverStripe\Versioned\Navigator\SilverStripeNavigatorItem_StageLink;
Done

2022-10-05 20:55 UTC, GuySartorelli commented on tests/Navigator/SilverStripeNavigatorTest.php
> +use SilverStripe\Dev\SapphireTest;
Done

2022-10-05 23:39 UTC, sabina-talipova approved these changes

2022-10-05 23:40 UTC, merged