ENH Allow File.keep_archived_assets to show files archive tab
silverstripe/silverstripe-versioned-admin pull request #301
Opened 2023-08-07 02:28 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-versioned-admin/issues/300

This should have been checked File.keep_archived_assets all along

2023-08-07 04:38 UTC, GuySartorelli requested changes

2023-08-07 04:38 UTC, GuySartorelli commented on src/Extensions/FileArchiveExtension.php
> +     *
```suggestion
```
This belongs as a code comment, not part of the PHPDoc

2023-08-07 04:38 UTC, GuySartorelli commented on src/Extensions/FileArchiveExtension.php
> +        return Config::inst()->get(AssetControlExtension::class, 'keep_archived_assets')
```suggestion
        // This should really only check File.keep_archived_assets, though it was originally
        // only checking AssetControlExtension.keep_archived_assets, so keeping that for BC
        return Config::inst()->get(AssetControlExtension::class, 'keep_archived_assets')
```

2023-08-07 21:54 UTC, emteknetnz commented on src/Extensions/FileArchiveExtension.php
> +        return Config::inst()->get(AssetControlExtension::class, 'keep_archived_assets')
Updated

2023-08-08 02:59 UTC, GuySartorelli approved these changes
Looks good, will merge when the remaining PRs are ready

2023-08-08 04:08 UTC, merged